[package]
name = "freecut"
version = "0.1.9"
authors = ["Gerhard Schwanzer <geri@sdf.org>"]
edition = "2018"

[dependencies]
cut-optimizer-2d = "0.1.1"
pdf-canvas = "0.6.0"
rand = "0.8.3"
comfy-table = "2.1.0"
fltk = "^0.15"
