name: Make

on:
  schedule:
    - cron:  '0 0 1 * *'
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "main"

env:
  CARGO_TERM_COLOR: always

jobs:
  make:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 120
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
        arch:
          - x86_64
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          submodules: recursive

      - name: Build on Unix
        if: runner.os != 'Windows'
        run: |
          sudo bash -c '
            apt-get update
            apt-get install -y lib{x11,xext,xft,xinerama,xcursor,xrender,xfixes,pango1.0,{gl1,glu1}-mesa}-dev
          ' >/dev/null
          cargo clippy --quiet
          cargo build --release
          cargo fmt --check --all

      - name: Build on Windows
        if: runner.os == 'Windows'
        shell: powershell
        run: |
          & cargo build | Out-Host
