name: Make

on:
  schedule:
    - cron:  '0 0 1 * *'
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "main"

env:
  CARGO_TERM_COLOR: always

jobs:
  make:
    runs-on: ubuntu-latest
    timeout-minutes: 120
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          submodules: recursive

      - name: Build
        run: |
          sudo bash -c '
            apt-get update
            apt-get install -y lib{x11,xext,xft,xinerama,xcursor,xrender,xfixes,pango1.0,{gl1,glu1}-mesa}-dev
          ' >/dev/null
          cargo clippy --quiet
          cargo build --release
          cargo fmt --check --all
